name: matlab

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  cmake:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        matlab: [latest]
        include:
        - os: macos-latest
          matlab: latest

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}
        cache: true

    - uses: actions/checkout@v4

    - name: CMake configure on Linux
      if: runner.os == 'Linux'
      run: cmake -Bbuild -Dfortran=yes
      env:
        CC: gcc-10
        CXX: g++-10
        FC: gfortran-10

    - name: CMake configure on macOS
      if: runner.os == 'macOS'
      run: cmake -Bbuild -Dfortran=no

    - name: CMake build
      run: cmake --build build

# MEX with CMake on GitHub runners gives
# Licensing error: -1,359. System Error: 2
# works with buildtool job.
    # - name: CMake Test MEX
    #   run: ctest --test-dir build -L mex -V

# Matlab Engine doesn't work on GitHub runners
    # - name: CMake Test Matlab Engine
    #   run: ctest --test-dir build -L engine -V

  buildtool:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        matlab: [latest]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}
        cache: true

    - uses: actions/checkout@v4

    - name: Check Matlab code
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Linux GCC 10
      if: runner.os == 'Linux'
      run: |
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
        echo "FC=gfortran-10" >> $GITHUB_ENV

    - name: Build MEX
      uses: matlab-actions/run-build@v2
      with:
        tasks: mex

    - name: Build engine
      uses: matlab-actions/run-build@v2
      with:
        tasks: engine

    - name: Test MEX
      uses: matlab-actions/run-build@v2
      with:
        tasks: test:mex

# Matlab Engine doesn't work on GitHub runners
    # - name: Test Matlab Engine
    #   uses: matlab-actions/run-build@v2
    #   with:
    #     tasks: test:engine
