name: matlab

on:
  push:
    paths:
    - "**.m"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Engine can't start on CI runner Linux, but works on real Linux computer

jobs:

  cmake:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        matlab: [R2023b, latest]
        include:
        - os: macos-latest
          matlab: latest

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}

    - uses: actions/checkout@v4

    - name: CMake Linux config
      if: runner.os == 'Linux'
      run: cmake -Bbuild -Dfortran=yes
      env:
        CC: gcc-10
        CXX: g++-10
        FC: gfortran-10

    - name: CMake macOS
      if: runner.os == 'macOS'
      run: cmake -Bbuild -Dfortran=no

    - name: Build
      run: cmake --build build

    #   it appears GitHub Actions license doesn't support running Mex executables
    # - name: Test
    #   run: ctest --test-dir build -LE engine -V


  buildtool:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        matlab: [latest]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:

    - name: Install MATLAB
      timeout-minutes: 10
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.matlab }}
        cache: true

    - uses: actions/checkout@v4

    - name: Check Matlab code
      uses: matlab-actions/run-build@v2
      with:
        tasks: check

    - name: Linux GCC 10
      if: runner.os == 'Linux'
      run: |
        echo "CC=gcc-10" >> $GITHUB_ENV
        echo "CXX=g++-10" >> $GITHUB_ENV
        echo "FC=gfortran-10" >> $GITHUB_ENV

    - name: Build MEX
      uses: matlab-actions/run-build@v2
      with:
        tasks: mex

    - name: Build engine
      uses: matlab-actions/run-build@v2
      with:
        tasks: engine

    - name: Test
      uses: matlab-actions/run-build@v2
      with:
        tasks: test

# it appears GitHub Actions license doesn't support running Mex executables
    # - name: Test
    #   run: ctest --test-dir build -C Release -LE engine -V
